const data = {
	brands: [
		{
			name: "Stellest",
			url: "https://www.essilor.com/en/innovation/stellest-lens/",
		},
		{ name: "Eyezen", url: "https://www.essilor.com/en/brands/eyezen/" },
		{ name: "Varilux", url: "https://www.essilor.com/en/brands/varilux/" },
		{ name: "Crizal", url: "https://www.essilor.com/en/brands/crizal/" },
		{
			name: "Transitions",
			url: "https://www.essilor.com/en/brands/transitions/",
		},
	],
	PH: {
		hero: { id: "PH", name: "Philippines" },
		items: [
			{
				id: "ph-001",
				name: "Crizal Anti-Reflective Coatings",
				description:
					"Popular for daily commuters and screen-heavy users thanks to glare reduction and smudge resistance.",
				url: "https://www.essilor.com/en/brands/crizal/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 3500,
				currency: "PHP",
				popularityScore: 8.2,
				frameColors: ["Black", "Clear", "Silver"],
				metrics: {
					searchInterest: 82,
					marketShare: 34,
					avgPrice: 3500,
					currency: "PHP",
				},
			},
			{
				id: "ph-002",
				name: "Eyezen Single-Vision",
				description:
					"Favored by young professionals to ease digital eye strain across mobile and desktop.",
				url: "https://www.essilor.com/en/brands/eyezen/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 3200,
				currency: "PHP",
				popularityScore: 7.6,
				frameColors: ["Matte Black", "Champagne"],
				metrics: {
					searchInterest: 76,
					marketShare: 29,
					avgPrice: 3200,
					currency: "PHP",
				},
			},
			{
				id: "ph-003",
				name: "Transitions Light Intelligent Lenses",
				description:
					"Strong tropical light drives interest in fast-activating photochromic lenses.",
				url: "https://www.essilor.com/en/brands/transitions/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 5200,
				currency: "PHP",
				popularityScore: 7.0,
				frameColors: ["Gray", "Brown"],
				metrics: {
					searchInterest: 70,
					marketShare: 23,
					avgPrice: 5200,
					currency: "PHP",
				},
			},
		],
	},
	SG: {
		hero: { id: "SG", name: "Singapore" },
		items: [
			{
				id: "sg-001",
				name: "Eyezen Single-Vision",
				description:
					"High screen-time market; blue-light and near-task comfort are key.",
				url: "https://www.essilor.com/en/brands/eyezen/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 240,
				currency: "SGD",
				popularityScore: 7.9,
				frameColors: ["Gray", "Gold"],
				metrics: {
					searchInterest: 79,
					marketShare: 31,
					avgPrice: 240,
					currency: "SGD",
				},
			},
			{
				id: "sg-002",
				name: "Crizal Anti-Reflective Coatings",
				description:
					"Urban lighting and frequent night driving increase demand for AR and clarity.",
				url: "https://www.essilor.com/en/brands/crizal/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 210,
				currency: "SGD",
				popularityScore: 7.4,
				frameColors: ["Black", "Silver"],
				metrics: {
					searchInterest: 74,
					marketShare: 28,
					avgPrice: 210,
					currency: "SGD",
				},
			},
			{
				id: "sg-003",
				name: "Stellest Myopia Management",
				description:
					"Growing pediatric myopia awareness drives adoption of evidence-based designs.",
				url: "https://www.essilor.com/en/innovation/stellest-lens/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 520,
				currency: "SGD",
				popularityScore: 6.7,
				frameColors: ["Clear", "Black"],
				metrics: {
					searchInterest: 67,
					marketShare: 19,
					avgPrice: 520,
					currency: "SGD",
				},
			},
		],
	},
	US: {
		hero: { id: "US", name: "United States" },
		items: [
			{
				id: "us-001",
				name: "Varilux Progressive Lenses",
				description:
					"Top choice for presbyopes seeking smooth distance-to-near transitions.",
				url: "https://www.essilor.com/en/brands/varilux/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 299,
				currency: "USD",
				popularityScore: 8.5,
				frameColors: ["Black", "Tortoise", "Silver"],
				metrics: {
					searchInterest: 85,
					marketShare: 36,
					avgPrice: 299,
					currency: "USD",
				},
			},
			{
				id: "us-002",
				name: "Crizal Anti-Reflective Coatings",
				description:
					"Reduces glare and halos for drivers and screen users alike.",
				url: "https://www.essilor.com/en/brands/crizal/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 179,
				currency: "USD",
				popularityScore: 8.0,
				frameColors: ["Gray", "Clear"],
				metrics: {
					searchInterest: 80,
					marketShare: 33,
					avgPrice: 179,
					currency: "USD",
				},
			},
			{
				id: "us-003",
				name: "Transitions Light Intelligent Lenses",
				description:
					"Photochromic convenience for mixed indoor/outdoor lifestyles.",
				url: "https://www.essilor.com/en/brands/transitions/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 229,
				currency: "USD",
				popularityScore: 7.3,
				frameColors: ["Gray", "Brown"],
				metrics: {
					searchInterest: 73,
					marketShare: 25,
					avgPrice: 229,
					currency: "USD",
				},
			},
		],
	},
	FR: {
		hero: { id: "FR", name: "France" },
		items: [
			{
				id: "fr-001",
				name: "Varilux Progressive Lenses",
				description:
					"Strong heritage market with preference for premium progressives.",
				url: "https://www.essilor.com/en/brands/varilux/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 279,
				currency: "EUR",
				popularityScore: 8.3,
				frameColors: ["Blue", "Black", "Silver"],
				metrics: {
					searchInterest: 83,
					marketShare: 35,
					avgPrice: 279,
					currency: "EUR",
				},
			},
			{
				id: "fr-002",
				name: "Crizal Anti-Reflective Coatings",
				description:
					"AR + smudge resistance popular for metro commuting and office work.",
				url: "https://www.essilor.com/en/brands/crizal/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 159,
				currency: "EUR",
				popularityScore: 7.7,
				frameColors: ["Gray", "Clear"],
				metrics: {
					searchInterest: 77,
					marketShare: 30,
					avgPrice: 159,
					currency: "EUR",
				},
			},
			{
				id: "fr-003",
				name: "Eyezen Single-Vision",
				description: "Digital eye strain relief for younger cohorts.",
				url: "https://www.essilor.com/en/brands/eyezen/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 179,
				currency: "EUR",
				popularityScore: 6.9,
				frameColors: ["Black", "Silver"],
				metrics: {
					searchInterest: 69,
					marketShare: 22,
					avgPrice: 179,
					currency: "EUR",
				},
			},
		],
	},
	IT: {
		hero: { id: "IT", name: "Italy" },
		items: [
			{
				id: "it-001",
				name: "Varilux Progressive Lenses",
				description:
					"Premium progressive adoption pairs well with fashion-forward frames.",
				url: "https://www.essilor.com/en/brands/varilux/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 269,
				currency: "EUR",
				popularityScore: 8.1,
				frameColors: ["Black", "Gold", "Tortoise"],
				metrics: {
					searchInterest: 81,
					marketShare: 33,
					avgPrice: 269,
					currency: "EUR",
				},
			},
			{
				id: "it-002",
				name: "Transitions Light Intelligent Lenses",
				description: "Sun-rich lifestyle favors on-the-go tint changes.",
				url: "https://www.essilor.com/en/brands/transitions/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 219,
				currency: "EUR",
				popularityScore: 7.2,
				frameColors: ["Gray", "Brown"],
				metrics: {
					searchInterest: 72,
					marketShare: 24,
					avgPrice: 219,
					currency: "EUR",
				},
			},
			{
				id: "it-003",
				name: "Crizal Anti-Reflective Coatings",
				description:
					"Clean aesthetics and clarity complement Italy’s design sensibilities.",
				url: "https://www.essilor.com/en/brands/crizal/",
				imageUrl: "/Icons/sunglasses.svg",
				price: 159,
				currency: "EUR",
				popularityScore: 7.4,
				frameColors: ["Black", "Clear"],
				metrics: {
					searchInterest: 74,
					marketShare: 26,
					avgPrice: 159,
					currency: "EUR",
				},
			},
		],
	},
};

export default data;
